from k_means_clustering.KMeansClustering import KMeansCluster
from k_means_optimal_clusters import k_means_cluster

k_means_cluster.visualise_cluster('./k_means_clustering/artifacts/world_map_clustered.png')